import { useState, useEffect, useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Bot, Sparkles, FileText, ListChecks, ChevronRight, ChevronLeft,
  Copy, Check, Loader, Users, ClipboardList, Zap, CheckCircle,
  Trash2, Upload, Brain, ChevronDown, ChevronUp, AlertTriangle
} from 'lucide-react'
import api from '../api/client'
import { renderMarkdown } from '../lib/markdown'
import { getApiErrorDetail } from '../lib/errors'
import { isAxiosError } from 'axios'
import SpeakerTab from './SpeakerTab'

// ── Types ─────────────────────────────────────────────────────
interface MomData {
  title?: string
  introduction?: string
  points_discussed?: string[]
  action_items?: Array<{ task: string; owner: string; deadline: string }>
  conclusion?: string
  participants?: string[]
  date?: string
}

interface Props {
  recordingId: string | null
  summary?: string
  shortSummary?: string
  detailedSummary?: string
  keyPoints?: string[]
  actionItems?: string[]
  speakerSummary?: Record<string, { summary: string; key_points: string[]; action_items: string[] }> | null
  /** MoM data auto-generated by pipeline — shown as the primary content */
  momData?: MomData | null
  isOpen: boolean
  onToggle: () => void
  /** True while AI insights are being generated */
  isGenerating?: boolean
  /** True while MoM is still being generated (pipeline phase 2) */
  isGeneratingMom?: boolean
  /** Callback when the user clicks "Generate AI Insights" */
  onGenerateInsights?: (tasks: string[]) => void
  /** True while the on-demand AI insight generation is running */
  isGeneratingInsights?: boolean
  /** Called when a segment jump is requested from the Speaker tab */
  onScrollToSegment?: (segId: string, startTime: number) => void
  /** Called after any Speaker-tab mutation so the parent can reload the transcript */
  onTranscriptChanged?: () => void
}

// ── Proper Markdown renderer using the lib ───────────────────
function MarkdownContent({ content, className }: { content: any; className?: string }) {
  return (
    <div
      className={`prose-ai ${className ?? ''}`}
      dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
    />
  )
}

function LocalAIBadge() {
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: '3px',
      fontSize: '.58rem', fontWeight: 700,
      background: 'hsl(var(--success) / .12)',
      color: 'hsl(var(--success))',
      border: '1px solid hsl(var(--success) / .3)',
      borderRadius: '4px', padding: '.05rem .32rem',
      letterSpacing: '.06em', textTransform: 'uppercase',
    }}>
      <Bot size={8} /> Local AI
    </span>
  )
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 1800)
  }
  return (
    <button
      onClick={copy}
      title="Copy"
      style={{
        background: 'none', border: 'none', cursor: 'pointer',
        color: 'hsl(var(--pencil))', padding: '3px 6px', borderRadius: '5px',
        display: 'flex', alignItems: 'center', gap: '4px',
        fontSize: '.68rem', fontFamily: 'Inter, sans-serif',
        transition: 'all .2s', opacity: 0.55,
      }}
      onMouseEnter={(e) => { const el = e.currentTarget as HTMLButtonElement; el.style.opacity = '1'; el.style.background = 'hsl(var(--muted))' }}
      onMouseLeave={(e) => { const el = e.currentTarget as HTMLButtonElement; el.style.opacity = '0.55'; el.style.background = 'none' }}
    >
      <span style={{ display: 'inline-block', transition: 'transform .2s', transform: copied ? 'rotateY(180deg)' : 'rotateY(0deg)' }}>
        {copied ? <Check size={11} style={{ color: 'hsl(var(--success))' }} /> : <Copy size={11} />}
      </span>
      {copied ? 'Copied!' : 'Copy'}
    </button>
  )
}

// ── Generating skeleton ───────────────────────────────────────
const GENERATING_MESSAGES = [
  'Analyzing transcript…',
  'Generating AI insights…',
  'Creating summary…',
  'Extracting key points…',
  'Identifying action items…',
  'Almost there…',
]

const MOM_GENERATING_MESSAGES = [
  'Analyzing meeting transcript…',
  'Drafting introduction…',
  'Identifying discussion points…',
  'Extracting action items…',
  'Writing conclusion…',
  'Finalizing minutes…',
]

function AIGeneratingSkeleton({ messages = GENERATING_MESSAGES }: { messages?: string[] }) {
  const [msgIdx, setMsgIdx] = useState(0)
  useEffect(() => {
    const t = setInterval(() => setMsgIdx(i => (i + 1) % messages.length), 2200)
    return () => clearInterval(t)
  }, [messages])
  return (
    <div style={{ padding: '1.25rem 1rem', display: 'flex', flexDirection: 'column', gap: '16px' }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px',
        padding: '.7rem .9rem',
        background: 'hsl(var(--accent) / .07)',
        borderRadius: '10px',
        border: '1px solid hsl(var(--accent) / .18)',
      }}>
        <Loader size={14} className="spin" style={{ color: 'hsl(var(--accent))', flexShrink: 0 }} />
        <span style={{ fontSize: '.78rem', fontFamily: 'Inter, sans-serif', color: 'hsl(var(--accent))', fontWeight: 600 }}>
          {messages[msgIdx]}
        </span>
      </div>
      {[{ w: '100%', h: 14 }, { w: '88%', h: 14 }, { w: '95%', h: 14 }, { w: '72%', h: 14 }].map((s, i) => (
        <div key={i} style={{
          height: `${s.h}px`, width: s.w, borderRadius: '6px',
          background: 'linear-gradient(90deg, hsl(var(--muted)) 0%, hsl(var(--card)) 50%, hsl(var(--muted)) 100%)',
          backgroundSize: '200% 100%', animation: `shimmer 1.8s ease-in-out infinite`, animationDelay: `${i * 0.15}s`,
        }} />
      ))}
      <div style={{ display: 'flex', gap: '8px', marginTop: '4px' }}>
        {[60, 45, 55].map((w, i) => (
          <div key={i} style={{
            height: '28px', width: `${w}%`, borderRadius: '6px',
            background: 'linear-gradient(90deg, hsl(var(--muted)) 0%, hsl(var(--card)) 50%, hsl(var(--muted)) 100%)',
            backgroundSize: '200% 100%', animation: `shimmer 1.8s ease-in-out infinite`, animationDelay: `${i * 0.2 + 0.6}s`,
          }} />
        ))}
      </div>
      <p style={{ fontSize: '.67rem', fontFamily: 'Inter, sans-serif', color: 'hsl(var(--pencil))', textAlign: 'center', marginTop: '8px', letterSpacing: '.03em' }}>
        Local AI · Running locally · Please wait
      </p>
    </div>
  )
}

// ── MoM Section renderer ──────────────────────────────────────
interface AttachmentFile {
  id: string
  filename: string
  type: 'agenda' | 'context'
}

type ProcessState = 'idle' | 'processing' | 'done' | 'error'

// ── MoM Section renderer ──────────────────────────────────────
function MomDisplay({ mom, recordingId }: { mom: MomData; recordingId: string }) {
  const navigate = useNavigate()
  const [pdfStatus, setPdfStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')

  // Defensively normalize mom properties to prevent crashes if raw backend shapes differ
  const safeTitle = typeof mom?.title === 'string' ? mom.title : ''
  const safeDate = typeof mom?.date === 'string' ? mom.date : ''
  const safeIntro = typeof mom?.introduction === 'string' ? mom.introduction : ''
  const safeConclusion = typeof mom?.conclusion === 'string' ? mom.conclusion : ''

  const participantsList: string[] = Array.isArray(mom?.participants)
    ? mom.participants.map(String)
    : typeof mom?.participants === 'string' && (mom.participants as string).trim()
    ? (mom.participants as string).split(',').map((s) => s.trim()).filter(Boolean)
    : []

  const pointsDiscussedList: string[] = Array.isArray(mom?.points_discussed)
    ? mom.points_discussed.map((pt: any) => {
        if (typeof pt === 'string') return pt
        if (pt && typeof pt === 'object') {
          if (pt.topic && pt.summary) return `${pt.topic}: ${pt.summary}`
          if (pt.summary) return String(pt.summary)
          if (pt.discussion_point) return String(pt.discussion_point)
          if (pt.text) return String(pt.text)
          return JSON.stringify(pt)
        }
        return String(pt)
      }).filter(Boolean)
    : []

  const actionItemsList: { task: string; owner?: string; deadline?: string }[] = Array.isArray(mom?.action_items)
    ? mom.action_items.map((ai: any) => {
        if (typeof ai === 'string') return { task: ai }
        if (ai && typeof ai === 'object') {
          return {
            task: String(ai.task || ai.item || ai.description || JSON.stringify(ai)),
            owner: ai.owner ? String(ai.owner) : undefined,
            deadline: ai.deadline ? String(ai.deadline) : undefined,
          }
        }
        return { task: String(ai) }
      }).filter(a => Boolean(a.task))
    : []

  // ── Attachment state ──────────────────────────────────────────
  const [contextPanelOpen, setContextPanelOpen] = useState(false)
  const [agendaFiles, setAgendaFiles] = useState<AttachmentFile[]>([])
  const [contextFiles, setContextFiles] = useState<AttachmentFile[]>([])
  const [agendaSummary, setAgendaSummary] = useState<string | null>(null)
  const [referenceSummary, setReferenceSummary] = useState<string | null>(null)
  const [agendaProcessState, setAgendaProcessState] = useState<ProcessState>('idle')
  const [contextProcessState, setContextProcessState] = useState<ProcessState>('idle')
  const agendaInputRef = useRef<HTMLInputElement>(null)
  const contextInputRef = useRef<HTMLInputElement>(null)

  // Fetch attachment files + summaries
  const fetchAttachments = useCallback(async () => {
    if (!recordingId) return
    try {
      const [attRes, sumRes] = await Promise.all([
        api.get(`/attachments/${recordingId}`),
        api.get(`/attachments/${recordingId}/summaries`),
      ])
      const allFiles: AttachmentFile[] = attRes.data.files || []
      setAgendaFiles(allFiles.filter(f => f.type === 'agenda'))
      setContextFiles(allFiles.filter(f => f.type === 'context'))
      setAgendaSummary(sumRes.data.agenda_summary || null)
      setReferenceSummary(sumRes.data.reference_summary || null)
    } catch (err) {
      console.error('[MomDisplay] Failed to fetch attachments:', err)
    }
  }, [recordingId])

  useEffect(() => {
    fetchAttachments()
  }, [fetchAttachments])

  const handleProcessFiles = async (type: 'agenda' | 'context') => {
    if (!recordingId) return
    const setState = type === 'agenda' ? setAgendaProcessState : setContextProcessState
    setState('processing')
    try {
      const formData = new FormData()
      formData.append('type', type)
      const res = await api.post(`/attachments/${recordingId}/process`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      })
      if (type === 'agenda') setAgendaSummary(res.data.summary)
      else setReferenceSummary(res.data.summary)
      setState('done')
    } catch (e) {
      console.error(`[MomDisplay] Processing failed for ${type}:`, e)
      setState('error')
    }
  }

  const handleUploadFiles = async (files: FileList | null, type: 'agenda' | 'context') => {
    if (!files || files.length === 0 || !recordingId) return
    const formData = new FormData()
    formData.append('type', type)
    Array.from(files).forEach(f => formData.append('files', f))
    try {
      await api.post(`/attachments/${recordingId}/upload`, formData, {
        headers: { 'Content-Type': 'multipart/form-data' },
      })
      // Refresh list
      const res = await api.get(`/attachments/${recordingId}`)
      const all: AttachmentFile[] = res.data.files || []
      const filtered = all.filter(f => f.type === type)
      if (type === 'agenda') setAgendaFiles(filtered)
      else setContextFiles(filtered)

      // Automatically generate/update summary in background
      if (filtered.length > 0) {
        await handleProcessFiles(type)
      }
    } catch (e) {
      alert(`Upload failed: ${getApiErrorDetail(e)}`)
    }
  }

  const handleDeleteFile = async (fileId: string, type: 'agenda' | 'context') => {
    if (!recordingId) return
    try {
      await api.delete(`/attachments/${recordingId}/${fileId}`)
      let remainingCount = 0
      if (type === 'agenda') {
        const remaining = agendaFiles.filter(f => f.id !== fileId)
        setAgendaFiles(remaining)
        remainingCount = remaining.length
        if (remainingCount === 0) setAgendaSummary(null)
      } else {
        const remaining = contextFiles.filter(f => f.id !== fileId)
        setContextFiles(remaining)
        remainingCount = remaining.length
        if (remainingCount === 0) setReferenceSummary(null)
      }

      // Automatically regenerate/update summary in background if files still exist
      if (remainingCount > 0) {
        await handleProcessFiles(type)
      }
    } catch (e) {
      alert(`Delete failed: ${getApiErrorDetail(e)}`)
    }
  }

  const handleDocx = async () => {
    setPdfStatus('loading')
    try {
      const res = await api.post(`/mom/${recordingId}/docx`, {}, { responseType: 'blob' })
      const blob = new Blob([res.data], { type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `MoM_${mom?.title?.replace(/\s+/g, '_') || 'Meeting'}.docx`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      setPdfStatus('success')
      setTimeout(() => setPdfStatus('idle'), 2500)
    } catch (err: unknown) {
      console.error('[MoMPdf] Failed:', err)
      setPdfStatus('error')
      setTimeout(() => setPdfStatus('idle'), 3000)
    }
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', padding: '.9rem 1rem' }}>

      {/* View & Download buttons */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '.5rem .75rem',
        background: 'hsl(var(--paper) / .4)',
        border: '1.5px solid hsl(var(--border) / .15)',
        borderRadius: '10px',
        marginBottom: '4px',
        gap: '10px',
      }}>
        <button
          onClick={() => navigate(`/dashboard/history/${recordingId}/mom`)}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            background: 'transparent',
            border: '1.5px solid hsl(var(--accent) / .4)',
            borderRadius: '6px',
            padding: '.35rem .75rem',
            fontSize: '.76rem',
            fontWeight: 600,
            color: 'hsl(var(--accent))',
            cursor: 'pointer',
            fontFamily: 'Inter, sans-serif',
            height: '32px',
            transition: 'all 0.15s ease',
          }}
          onMouseEnter={e => {
            e.currentTarget.style.background = 'hsl(var(--accent) / .08)'
            e.currentTarget.style.borderColor = 'hsl(var(--accent))'
          }}
          onMouseLeave={e => {
            e.currentTarget.style.background = 'transparent'
            e.currentTarget.style.borderColor = 'hsl(var(--accent) / .4)'
          }}
        >
          <FileText size={13} />
          <span>View MoM Page</span>
        </button>

        <button
          onClick={handleDocx}
          disabled={pdfStatus === 'loading'}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            background: 'transparent',
            border: `1.5px solid ${pdfStatus === 'error' ? 'hsl(var(--destructive))' : pdfStatus === 'success' ? 'hsl(var(--success))' : 'hsl(var(--pencil) / .3)'}`,
            borderRadius: '6px',
            padding: '.35rem .75rem',
            fontSize: '.76rem',
            fontWeight: 600,
            color: pdfStatus === 'error' ? 'hsl(var(--destructive))' : pdfStatus === 'success' ? 'hsl(var(--success))' : 'hsl(var(--ink-soft))',
            cursor: pdfStatus === 'loading' ? 'not-allowed' : 'pointer',
            fontFamily: 'Inter, sans-serif',
            height: '32px',
            transition: 'all 0.15s ease',
          }}
          onMouseEnter={e => {
            if (pdfStatus === 'idle') {
              e.currentTarget.style.background = 'hsl(var(--muted))'
              e.currentTarget.style.borderColor = 'hsl(var(--pencil) / .6)'
            }
          }}
          onMouseLeave={e => {
            if (pdfStatus === 'idle') {
              e.currentTarget.style.background = 'transparent'
              e.currentTarget.style.borderColor = 'hsl(var(--pencil) / .3)'
            }
          }}
        >
          {pdfStatus === 'loading' ? (
            <Loader size={13} className="spin" />
          ) : pdfStatus === 'success' ? (
            <Check size={13} style={{ color: 'hsl(var(--success))' }} />
          ) : (
            <FileText size={13} />
          )}
          <span>
            {pdfStatus === 'loading'
              ? 'Downloading…'
              : pdfStatus === 'success'
              ? 'Downloaded!'
              : pdfStatus === 'error'
              ? 'Failed'
              : 'Download DOCX'}
          </span>
        </button>
      </div>

      {/* ── Collapsible AI Context Files Section (Sidebar Version) ── */}
      <div style={{
        borderRadius: '10px',
        border: '1.5px solid hsl(var(--border) / .15)',
        background: 'hsl(var(--card))',
        overflow: 'hidden',
      }}>
        <button
          onClick={() => setContextPanelOpen(v => !v)}
          style={{
            width: '100%', display: 'flex', alignItems: 'center', gap: '8px',
            padding: '0.65rem 0.85rem', background: 'transparent', border: 'none',
            cursor: 'pointer', color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif',
            fontSize: '0.78rem', fontWeight: 600,
          }}
        >
          <Brain size={13} style={{ color: 'hsl(var(--accent))' }} />
          <span style={{ flex: 1, textAlign: 'left' }}>AI Context Files</span>
          {(agendaSummary || referenceSummary) && (
            <span style={{
              fontSize: '0.6rem', padding: '0.08rem 0.4rem', borderRadius: '99px',
              background: 'hsl(var(--accent) / .12)', color: 'hsl(var(--accent))',
              fontWeight: 700, marginRight: 4,
            }}>Active</span>
          )}
          <span style={{ color: 'hsl(var(--pencil))' }}>
            {contextPanelOpen ? <ChevronUp size={13} /> : <ChevronDown size={13} />}
          </span>
        </button>

        {contextPanelOpen && (
          <div style={{ padding: '0 0.85rem 0.85rem', display: 'flex', flexDirection: 'column', gap: '0.75rem', borderTop: '1px solid hsl(var(--border) / .1)' }}>
            
            {/* Hidden file inputs */}
            <input ref={agendaInputRef} type="file" multiple accept=".pdf,.docx,.pptx,.txt,.md,.png,.jpg,.jpeg,.webp" style={{ display: 'none' }}
              onChange={e => handleUploadFiles(e.target.files, 'agenda')} />
            <input ref={contextInputRef} type="file" multiple accept=".pdf,.docx,.pptx,.txt,.md,.png,.jpg,.jpeg,.webp" style={{ display: 'none' }}
              onChange={e => handleUploadFiles(e.target.files, 'context')} />

            {/* Agenda section */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.72rem', fontWeight: 700, color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif' }}>
                <FileText size={11} style={{ color: 'hsl(var(--accent))' }} />
                <span>Agenda Files</span>
                {agendaProcessState === 'processing' && <Loader size={10} className="spin" style={{ marginLeft: 'auto', color: 'hsl(var(--accent))' }} />}
              </div>

              {agendaFiles.length > 0 && (
                <div style={{ display: 'flex', flexDirection: 'column', gap: '3px', marginTop: '2px' }}>
                  {agendaFiles.map(f => (
                    <div key={f.id} style={{ display: 'flex', alignItems: 'center', gap: '4px', padding: '3px 6px', borderRadius: '5px', background: 'hsl(var(--muted) / .4)', fontSize: '0.72rem', fontFamily: 'Inter, sans-serif' }}>
                      <FileText size={10} style={{ flexShrink: 0, color: 'hsl(var(--pencil))' }} />
                      <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap', color: 'hsl(var(--ink))' }}>{f.filename}</span>
                      <button onClick={() => handleDeleteFile(f.id, 'agenda')} style={{ background: 'none', border: 'none', cursor: 'pointer', padding: '1px', color: 'hsl(var(--destructive))', flexShrink: 0 }}>
                        <Trash2 size={10} />
                      </button>
                    </div>
                  ))}
                </div>
              )}

              <div
                onClick={() => agendaInputRef.current?.click()}
                style={{
                  border: '1.2px dashed hsl(var(--border) / .6)', borderRadius: '6px',
                  padding: '0.45rem', textAlign: 'center', cursor: 'pointer',
                  fontSize: '0.72rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif',
                  display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '4px',
                  background: 'hsl(var(--paper) / .3)',
                }}
              >
                <Upload size={10} /> Upload Agenda
              </div>

              {agendaSummary && (
                <div style={{ padding: '0.45rem 0.55rem', borderRadius: '6px', background: 'hsl(var(--accent) / .07)', border: '1px solid hsl(var(--accent) / .2)', marginTop: '2px' }}>
                  <p style={{ fontSize: '0.65rem', fontWeight: 700, color: 'hsl(var(--accent))', fontFamily: 'Inter, sans-serif', marginBottom: '2px' }}>Agenda Summary ✓</p>
                  <p style={{ fontSize: '0.68rem', color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif', lineHeight: 1.5, whiteSpace: 'pre-wrap', maxHeight: '60px', overflowY: 'auto' }}>{agendaSummary}</p>
                </div>
              )}
            </div>

            {/* Context section */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: '4px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '4px', fontSize: '0.72rem', fontWeight: 700, color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif' }}>
                <FileText size={11} style={{ color: '#8b5cf6' }} />
                <span>Context Files</span>
                {contextProcessState === 'processing' && <Loader size={10} className="spin" style={{ marginLeft: 'auto', color: '#8b5cf6' }} />}
              </div>

              {contextFiles.length > 0 && (
                <div style={{ display: 'flex', flexWrap: 'wrap', gap: '4px', marginTop: '2px' }}>
                  {contextFiles.map(f => (
                    <span key={f.id} style={{
                      display: 'inline-flex', alignItems: 'center', gap: '4px',
                      padding: '2px 6px', borderRadius: '4px',
                      background: 'hsl(var(--card))', border: '1px solid hsl(var(--border) / .3)',
                      fontSize: '.67rem', color: 'hsl(var(--ink-soft))', fontFamily: 'Inter, sans-serif',
                    }}>
                      📁 {f.filename}
                      <button
                        onClick={() => handleDeleteFile(f.id, 'context')}
                        style={{ border: 'none', background: 'transparent', cursor: 'pointer', padding: 0, color: 'hsl(var(--pencil))' }}
                      >
                        <Trash2 size={9} />
                      </button>
                    </span>
                  ))}
                </div>
              )}

              {referenceSummary && (
                <div style={{ padding: '0.45rem 0.55rem', borderRadius: '6px', background: 'hsl(#8b5cf6 / .07)', border: '1px solid hsl(#8b5cf6 / .2)', borderColor: '#8b5cf620', marginTop: '2px' }}>
                  <p style={{ fontSize: '0.65rem', fontWeight: 700, color: '#8b5cf6', fontFamily: 'Inter, sans-serif', marginBottom: '2px' }}>Context Summary ✓</p>
                  <p style={{ fontSize: '0.68rem', color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif', lineHeight: 1.5, whiteSpace: 'pre-wrap', maxHeight: '60px', overflowY: 'auto' }}>{referenceSummary}</p>
                </div>
              )}
            </div>

          </div>
        )}
      </div>

      {/* Title */}
      {safeTitle && (
        <div style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: '.95rem',
          fontWeight: 700,
          color: 'hsl(var(--ink))',
          letterSpacing: '-.01em',
          lineHeight: 1.3,
        }}>
          {safeTitle}
        </div>
      )}

      {/* Meta row */}
      {(safeDate || participantsList.length > 0) && (
        <div style={{
          display: 'flex', gap: '8px', flexWrap: 'wrap',
          fontSize: '.7rem', color: 'hsl(var(--pencil))',
          fontFamily: 'Inter, sans-serif',
        }}>
          {safeDate && <span>📅 {safeDate}</span>}
          {participantsList.length > 0 && (
            <span>👥 {participantsList.join(', ')}</span>
          )}
        </div>
      )}

      {/* Introduction */}
      {safeIntro && (
        <div style={{
          background: 'linear-gradient(135deg, hsl(var(--accent) / .06), hsl(var(--accent) / .02))',
          border: '1px solid hsl(var(--accent) / .2)',
          borderLeft: '3px solid hsl(var(--accent))',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--accent))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '6px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <FileText size={10} /> Introduction
          </div>
          <p style={{
            fontSize: '.83rem', color: 'hsl(var(--ink-soft))',
            fontFamily: 'Inter, sans-serif', lineHeight: 1.65, margin: 0,
          }}>
            {safeIntro}
          </p>
        </div>
      )}

      {/* Points discussed */}
      {pointsDiscussedList.length > 0 && (
        <div style={{
          background: 'hsl(var(--card))',
          border: '1px solid hsl(var(--border) / .25)',
          borderLeft: '3px solid hsl(280,70%,60%)',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(280,70%,50%)',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '8px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <ListChecks size={10} /> Points Discussed
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
            {pointsDiscussedList.map((pt, i) => {
              // If point has "Topic: Summary" format, bold the topic
              const colonIdx = pt.indexOf(': ')
              const topic = colonIdx > 0 && colonIdx < 80 ? pt.slice(0, colonIdx) : null
              const body = topic ? pt.slice(colonIdx + 2) : pt
              return (
                <div key={i} style={{
                  fontSize: '.82rem', color: 'hsl(var(--ink-soft))',
                  paddingLeft: '.9rem', position: 'relative',
                  lineHeight: 1.55, fontFamily: 'Inter, sans-serif',
                }}>
                  <span style={{ position: 'absolute', left: 0, color: 'hsl(280,70%,50%)', fontWeight: 700 }}>•</span>
                  {topic ? (
                    <>
                      <span style={{ fontWeight: 700, color: 'hsl(var(--ink))' }}>{topic}:</span>{' '}
                      {body}
                    </>
                  ) : pt}
                </div>
              )
            })}
          </div>
        </div>
      )}

      {/* Action items */}
      {actionItemsList.length > 0 && (
        <div style={{
          background: 'hsl(var(--card))',
          border: '1px solid hsl(var(--success) / .2)',
          borderLeft: '3px solid hsl(var(--success))',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--success))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '8px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <CheckCircle size={10} /> Action Items
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
            {actionItemsList.map((ai, i) => (
              <div key={i} style={{
                fontSize: '.8rem', color: 'hsl(var(--ink-soft))',
                lineHeight: 1.55, fontFamily: 'Inter, sans-serif',
                display: 'flex', gap: '6px', alignItems: 'flex-start',
              }}>
                <span style={{ color: 'hsl(var(--success))', fontSize: '.9rem', flexShrink: 0 }}>☐</span>
                <span>
                  {ai.task}
                  {ai.owner && (
                    <span style={{ color: 'hsl(var(--pencil))', fontSize: '.72rem', marginLeft: '4px' }}>— {ai.owner}</span>
                  )}
                  {ai.deadline && (
                    <span style={{ color: 'hsl(var(--pencil))', fontSize: '.72rem', marginLeft: '4px' }}>({ai.deadline})</span>
                  )}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Conclusion */}
      {safeConclusion && (
        <div style={{
          background: 'hsl(var(--muted) / .5)',
          border: '1px solid hsl(var(--border) / .2)',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--pencil))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '6px', fontFamily: 'Inter, sans-serif',
          }}>
            Conclusion
          </div>
          <p style={{
            fontSize: '.82rem', color: 'hsl(var(--ink-soft))',
            fontFamily: 'Inter, sans-serif', lineHeight: 1.65, margin: 0,
          }}>
            {safeConclusion}
          </p>
        </div>
      )}
    </div>
  )
}

// ── Action Items renderer (General + Speaker sections) ────────
// ── Action Items renderer (Improved) ───────────────────────────
function ActionItemsRenderer({ items }: { items: string[] }) {
  if (!items || items.length === 0) return null

  type Section = {
    header: string
    items: string[]
  }

  let sections: Section[] = []

  // -------------------------------------------------------
  // Try parsing JSON first
  // -------------------------------------------------------
  if (
    items.length === 1 &&
    (items[0].trim().startsWith("{") || items[0].trim().startsWith("["))
  ) {
    try {
      const json = JSON.parse(items[0])

      if (json.general_action_items?.length) {
        sections.push({
          header: "General Action Items",
          items: json.general_action_items,
        })
      }

      if (json.speaker_action_items) {
        Object.entries(json.speaker_action_items).forEach(([speaker, value]) => {
          sections.push({
            header: speaker,
            items: value as string[],
          })
        })
      }
    } catch {
      // Ignore and continue with normal parsing
    }
  }

  // -------------------------------------------------------
  // Normal text parser
  // -------------------------------------------------------
  if (sections.length === 0) {
    let current: Section = {
      header: "General Action Items",
      items: [],
    }

    sections.push(current)

    for (const raw of items) {
      if (raw === null || raw === undefined) continue

      let line = ''
      if (typeof raw === 'object') {
        const itemObj = raw as any
        const taskText = itemObj.task || itemObj.text || itemObj.action || itemObj.description || JSON.stringify(itemObj)
        const owner = itemObj.owner ? ` (${itemObj.owner})` : ''
        const deadline = itemObj.deadline ? ` [${itemObj.deadline}]` : ''
        current.items.push(`${taskText}${owner}${deadline}`)
        continue
      } else {
        line = String(raw).trim()
      }

      if (!line) continue

      const cleaned = line
        .replace(/^#+\s*/, "")
        .replace(/:$/, "")

      const isBullet =
        /^[-*•]\s+/.test(line) ||
        /^\d+\.\s+/.test(line)

      if (!isBullet) {
        current = {
          header: cleaned,
          items: [],
        }
        sections.push(current)
        continue
      }

      current.items.push(
        line
          .replace(/^[-*•]\s*/, "")
          .replace(/^\d+\.\s*/, "")
          .trim()
      )
    }

    sections = sections.filter(s => s.items.length)
  }

  // -------------------------------------------------------
  // Render
  // -------------------------------------------------------

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
      {sections.map((section, sectionIndex) => {
        const isGeneral = /general/i.test(section.header)

        return (
          <div key={sectionIndex}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                marginBottom: "10px",
                paddingBottom: "6px",
                borderBottom: "1px solid hsl(var(--border) / .25)",

                fontSize: ".70rem",
                fontWeight: 700,
                textTransform: "uppercase",
                letterSpacing: ".08em",

                color: isGeneral
                  ? "hsl(var(--accent))"
                  : "hsl(var(--ink))",
              }}
            >
              {!isGeneral && (
                <span
                  style={{
                    width: 18,
                    height: 18,
                    borderRadius: "50%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",

                    background: `hsl(${(sectionIndex * 137) % 360},70%,90%)`,
                    color: `hsl(${(sectionIndex * 137) % 360},70%,35%)`,

                    fontSize: ".62rem",
                    fontWeight: 700,
                  }}
                >
                  {section.header.charAt(0).toUpperCase()}
                </span>
              )}


              <MarkdownContent content={section.header} />
            </div>

            {section.items.map((item, i) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "8px",
                  marginBottom: "8px",
                }}
              >
                <span
                  style={{
                    color: isGeneral
                      ? "hsl(var(--accent))"
                      : "hsl(var(--success))",
                    fontSize: ".9rem",
                    marginTop: "2px",
                    flexShrink: 0,
                  }}
                >
                  ☐
                </span>

                <div style={{ flex: 1 }}>
                  <MarkdownContent content={item} />
                </div>
              </div>
            ))}
          </div>
        )
      })}
    </div>
  )
}
// ── Main Component ────────────────────────────────────────────
export default function AIChatPanel({
  recordingId,
  summary,
  shortSummary,
  detailedSummary,
  keyPoints,
  actionItems,
  speakerSummary,
  momData,
  isOpen,
  onToggle,
  isGenerating = false,
  isGeneratingMom = false,
  onGenerateInsights,
  isGeneratingInsights = false,
  onScrollToSegment,
  onTranscriptChanged,
}: Props) {
  const navigate = useNavigate()
  const [summaryTab, setSummaryTab] = useState<'short' | 'detailed' | 'speaker'>('short')
  const [activeView, setActiveView] = useState<'mom' | 'insights' | 'speakers'>('mom')
  const [localMomData, setLocalMomData] = useState<MomData | null>(null)
  const [isGeneratingLocalMom, setIsGeneratingLocalMom] = useState(false)
  const [localMomError, setLocalMomError] = useState<string | null>(null)

  const handleGenerateMomPanel = async () => {
    if (!recordingId || isGeneratingLocalMom) return
    setIsGeneratingLocalMom(true)
    setLocalMomError(null)
    try {
      const res = await api.post(`/mom/${recordingId}/generate`)
      setLocalMomData(res.data)
    } catch (err: unknown) {
      setLocalMomError(getApiErrorDetail(err, 'Failed to generate MoM.'))
    } finally {
      setIsGeneratingLocalMom(false)
    }
  }

  const resolvedShort = shortSummary || summary || ''
  const resolvedDetailed = detailedSummary || ''

  const currentMom = localMomData || momData
  const hasMom = currentMom && (currentMom.title || currentMom.introduction || (currentMom.points_discussed && currentMom.points_discussed.length > 0))
  const hasInsights = resolvedShort || resolvedDetailed || keyPoints?.length || actionItems?.length || (speakerSummary && Object.keys(speakerSummary).length > 0)

  const showGeneratingSkeleton = isGenerating && !hasInsights
  const showMomGenerating = (isGeneratingMom || isGeneratingLocalMom) && !hasMom

  /* ── Collapsed strip */
  if (!isOpen) {
    return (
      <div style={{
        display: 'flex', flexDirection: 'column', alignItems: 'center',
        paddingTop: '.75rem',
        background: 'hsl(var(--card))',
        borderLeft: '1.5px solid hsl(var(--border) / .2)',
      }}>
        <button className="icon-btn" onClick={onToggle} title="Open AI & MoM Panel" style={{ marginBottom: '12px' }}>
          <ChevronLeft size={16} />
        </button>
        <div style={{
          width: '34px', height: '34px', borderRadius: '10px',
          background: 'linear-gradient(135deg, hsl(var(--accent) / .15), hsl(var(--accent) / .05))',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          border: '1.5px solid hsl(var(--accent) / .3)',
          boxShadow: '0 0 12px hsl(var(--accent) / .1)',
        }}>
          <ClipboardList size={17} style={{ color: 'hsl(var(--accent))' }} />
        </div>
        {(hasMom || hasInsights || isGenerating || isGeneratingMom) && (
          <div style={{
            marginTop: '10px',
            width: '8px', height: '8px',
            borderRadius: '50%',
            background: (isGenerating || isGeneratingMom) ? 'hsl(var(--accent))' : 'hsl(var(--success))',
            boxShadow: (isGenerating || isGeneratingMom) ? '0 0 8px hsl(var(--accent) / .6)' : '0 0 8px hsl(var(--success) / .6)',
          }} className="animate-pulse-rec" />
        )}
      </div>
    )
  }

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', height: '100%',
      background: 'hsl(var(--card))',
      borderLeft: '1.5px solid hsl(var(--border) / .2)',
      overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px',
        padding: '.9rem 1rem',
        borderBottom: '1.5px solid hsl(var(--border) / .2)',
        background: 'linear-gradient(180deg, hsl(var(--card)) 0%, hsl(var(--card) / .9) 100%)',
        backdropFilter: 'blur(8px)',
        flexShrink: 0,
        minHeight: '58px',
      }}>
        <div style={{
          width: '32px', height: '32px', borderRadius: '9px', flexShrink: 0,
          background: 'linear-gradient(135deg, hsl(var(--accent) / .18), hsl(var(--accent) / .06))',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          border: '1.5px solid hsl(var(--accent) / .35)',
          boxShadow: '0 0 14px hsl(var(--accent) / .12)',
        }}>
          <ClipboardList size={16} style={{ color: 'hsl(var(--accent))' }} />
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{
            fontSize: '.88rem', fontWeight: 700, fontFamily: 'Inter, sans-serif',
            color: 'hsl(var(--ink))', lineHeight: 1.2,
            display: 'flex', alignItems: 'center', gap: '6px',
          }}>
            AI & MoM Panel
            <LocalAIBadge />
          </div>
          <div style={{ fontSize: '.65rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif', marginTop: '2px' }}>
            Runs entirely on this machine · Fully offline
          </div>
        </div>
        <button className="icon-btn" onClick={onToggle} title="Collapse panel" style={{ width: '30px', height: '30px', flexShrink: 0 }}>
          <ChevronRight size={14} />
        </button>
      </div>

      {/* View selector tabs — only when recording is selected */}
      {recordingId && (
        <div style={{
          display: 'flex', gap: 0,
          borderBottom: '1px solid hsl(var(--border) / .18)',
          padding: '0 .75rem',
          flexShrink: 0,
          background: 'hsl(var(--paper) / .3)',
        }}>
          <button
            onClick={() => setActiveView('mom')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '.55rem .75rem',
              fontSize: '.72rem', fontWeight: 700,
              fontFamily: 'Inter, sans-serif',
              textTransform: 'uppercase', letterSpacing: '.07em',
              color: activeView === 'mom' ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
              borderBottom: activeView === 'mom' ? '2px solid hsl(var(--accent))' : '2px solid transparent',
              marginBottom: '-1px', transition: 'color .18s',
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <ClipboardList size={10} /> MoM
            {(hasMom) && <span style={{
              width: '6px', height: '6px', borderRadius: '50%',
              background: 'hsl(var(--success))', flexShrink: 0,
            }} />}
          </button>
          <button
            onClick={() => setActiveView('insights')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '.55rem .75rem',
              fontSize: '.72rem', fontWeight: 700,
              fontFamily: 'Inter, sans-serif',
              textTransform: 'uppercase', letterSpacing: '.07em',
              color: activeView === 'insights' ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
              borderBottom: activeView === 'insights' ? '2px solid hsl(var(--accent))' : '2px solid transparent',
              marginBottom: '-1px', transition: 'color .18s',
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <Sparkles size={10} /> AI Insights
            {hasInsights && <span style={{
              width: '6px', height: '6px', borderRadius: '50%',
              background: 'hsl(var(--success))', flexShrink: 0,
            }} />}
          </button>
          <button
            onClick={() => setActiveView('speakers')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '.55rem .75rem',
              fontSize: '.72rem', fontWeight: 700,
              fontFamily: 'Inter, sans-serif',
              textTransform: 'uppercase', letterSpacing: '.07em',
              color: activeView === 'speakers' ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
              borderBottom: activeView === 'speakers' ? '2px solid hsl(var(--accent))' : '2px solid transparent',
              marginBottom: '-1px', transition: 'color .18s',
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <Users size={10} /> Speakers
          </button>
        </div>
      )}

      {/* Content area */}
      <div style={{ flex: 1, overflowY: 'auto', minHeight: 0 }}>

        {/* No recording selected */}
        {!recordingId && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '2rem', gap: '14px', textAlign: 'center' }}>
            <div style={{
              width: '56px', height: '56px', borderRadius: '16px',
              background: 'linear-gradient(135deg, hsl(var(--accent) / .12), hsl(var(--accent) / .04))',
              border: '1.5px solid hsl(var(--accent) / .25)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              boxShadow: '0 0 20px hsl(var(--accent) / .08)',
            }}>
              <ClipboardList size={24} style={{ color: 'hsl(var(--accent))' }} className="animate-float" />
            </div>
            <div>
              <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.88rem', color: 'hsl(var(--ink))', fontWeight: 600, marginBottom: '.3rem' }}>
                AI & MoM Panel
              </p>
              <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.78rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '380px', margin: '0 auto' }}>
                Process a recording to see the auto-generated Minutes of Meeting and AI insights
              </p>
            </div>
          </div>
        )}

        {/* ── MoM Tab ── */}
        {recordingId && activeView === 'mom' && (
          <>
            {/* MoM generating skeleton */}
            {showMomGenerating && (
              <AIGeneratingSkeleton messages={MOM_GENERATING_MESSAGES} />
            )}

            {/* MoM ready */}
            {!showMomGenerating && hasMom && (
              <MomDisplay mom={currentMom!} recordingId={recordingId} />
            )}

            {/* No MoM yet (pipeline done, MoM failed or not yet run) */}
            {!showMomGenerating && !hasMom && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '2rem 1.25rem', gap: '14px', textAlign: 'center' }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '16px',
                  background: 'linear-gradient(135deg, hsl(var(--accent) / .12), hsl(var(--accent) / .04))',
                  border: '1.5px solid hsl(var(--accent) / .25)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <ClipboardList size={24} style={{ color: 'hsl(var(--accent))' }} />
                </div>
                <div>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.88rem', color: 'hsl(var(--ink))', fontWeight: 600, marginBottom: '.3rem' }}>
                    No MoM Available
                  </p>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.78rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '260px', margin: '0 auto' }}>
                    Generate Minutes of Meeting now.
                  </p>
                </div>
                {localMomError && (
                  <div style={{ padding: '0.5rem 0.75rem', borderRadius: '8px', background: 'hsl(var(--destructive) / .1)', border: '1px solid hsl(var(--destructive) / .25)', color: 'hsl(var(--destructive))', fontSize: '0.75rem', fontFamily: 'Inter, sans-serif' }}>
                    <AlertTriangle size={12} style={{ display: 'inline', marginRight: '4px' }} />
                    {localMomError}
                  </div>
                )}
                <div style={{ display: 'flex', flexDirection: 'column', gap: '8px', width: '100%', maxWidth: '240px' }}>
                  <button
                    id="panel-btn-generate-mom"
                    onClick={handleGenerateMomPanel}
                    disabled={isGeneratingLocalMom}
                    style={{
                      display: 'flex', alignItems: 'center', justifyContent: 'center', gap: '6px',
                      padding: '.55rem 1rem',
                      background: 'linear-gradient(135deg, hsl(var(--accent)), hsl(var(--accent) / .8))',
                      color: 'white', border: 'none', borderRadius: '8px',
                      fontSize: '.8rem', fontWeight: 700, fontFamily: 'Inter, sans-serif',
                      cursor: 'pointer', boxShadow: '0 3px 10px hsl(var(--accent) / .25)',
                    }}
                  >
                    {isGeneratingLocalMom ? <Loader size={14} className="spin" /> : <Sparkles size={14} />}
                    {isGeneratingLocalMom ? 'Generating...' : 'Generate MoM'}
                  </button>
                </div>
              </div>
            )}
          </>
        )}

        {/* ── AI Insights Tab ── */}
        {recordingId && activeView === 'insights' && (
          <>
            {/* Generating skeleton for AI insights */}
            {showGeneratingSkeleton && (
              <AIGeneratingSkeleton />
            )}

            {/* Generate AI Insights button — shown when no insights yet */}
            {!showGeneratingSkeleton && !hasInsights && (
              <div style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center',
                justifyContent: 'center', height: '100%',
                padding: '2rem', gap: '16px', textAlign: 'center',
              }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '16px',
                  background: 'linear-gradient(135deg, hsl(var(--accent) / .12), hsl(var(--accent) / .04))',
                  border: '1.5px solid hsl(var(--accent) / .25)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 20px hsl(var(--accent) / .08)',
                }}>
                  <Sparkles size={24} style={{ color: 'hsl(var(--accent))' }} className="animate-float" />
                </div>
                <div>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.88rem', color: 'hsl(var(--ink))', fontWeight: 600, marginBottom: '.3rem' }}>
                    AI Insights
                  </p>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.78rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '240px', margin: '0 auto .75rem' }}>
                    Generate a summary, key points, and action items from this recording
                  </p>
                </div>
                {onGenerateInsights && (
                  <button
                    id="generate-insights-btn"
                    onClick={() => onGenerateInsights(['short_summary', 'detailed_summary', 'key_points', 'action_items'])}
                    disabled={isGeneratingInsights}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '8px',
                      padding: '.65rem 1.4rem',
                      background: isGeneratingInsights
                        ? 'hsl(var(--muted))'
                        : 'linear-gradient(135deg, hsl(var(--accent)), hsl(var(--accent) / .8))',
                      color: isGeneratingInsights ? 'hsl(var(--pencil))' : 'white',
                      border: 'none', borderRadius: '10px',
                      fontSize: '.85rem', fontWeight: 700,
                      fontFamily: 'Inter, sans-serif',
                      cursor: isGeneratingInsights ? 'not-allowed' : 'pointer',
                      boxShadow: isGeneratingInsights ? 'none' : '0 4px 14px hsl(var(--accent) / .3)',
                      transition: 'all .2s',
                    }}
                  >
                    {isGeneratingInsights
                      ? <><Loader size={15} className="spin" /> Generating…</>
                      : <><Zap size={15} /> Generate AI Insights</>
                    }
                  </button>
                )}
              </div>
            )}

            {/* AI insights loaded — show full panel */}
            {hasInsights && (
              <>
                {/* Re-generate button strip at top when insights already exist */}
                {onGenerateInsights && (
                  <div style={{
                    padding: '.55rem 1rem',
                    borderBottom: '1px solid hsl(var(--border) / .15)',
                    display: 'flex', justifyContent: 'flex-end',
                    background: 'hsl(var(--paper) / .3)',
                    flexShrink: 0,
                  }}>
                    <button
                      onClick={() => onGenerateInsights(['short_summary', 'detailed_summary', 'key_points', 'action_items'])}
                      disabled={isGeneratingInsights}
                      style={{
                        display: 'flex', alignItems: 'center', gap: '5px',
                        padding: '.3rem .7rem',
                        background: 'none',
                        color: 'hsl(var(--accent))',
                        border: '1.5px solid hsl(var(--accent) / .3)',
                        borderRadius: '7px',
                        fontSize: '.7rem', fontWeight: 700,
                        fontFamily: 'Inter, sans-serif',
                        cursor: isGeneratingInsights ? 'not-allowed' : 'pointer',
                        opacity: isGeneratingInsights ? 0.5 : 1,
                        transition: 'all .2s',
                      }}
                    >
                      {isGeneratingInsights
                        ? <><Loader size={11} className="spin" /> Generating…</>
                        : <><Zap size={11} /> Regenerate</>
                      }
                    </button>
                  </div>
                )}

                {/* Tabbed Summary Card */}
                {(resolvedShort || resolvedDetailed || (speakerSummary && Object.keys(speakerSummary).length > 0)) && (
                  <div style={{
                    borderBottom: '1.5px solid hsl(var(--border) / .2)',
                    background: 'hsl(var(--paper) / .4)',
                  }}>
                    {/* Tab strip */}
                    <div style={{ display: 'flex', gap: 0, borderBottom: '1px solid hsl(var(--border) / .18)', padding: '0 .75rem' }}>
                      {([
                        ...(resolvedShort ? [{ id: 'short', label: 'Short', icon: <Sparkles size={10} /> }] : []),
                        ...(resolvedDetailed ? [{ id: 'detailed', label: 'Detailed', icon: <FileText size={10} /> }] : []),
                        ...(speakerSummary && Object.keys(speakerSummary).length > 0
                          ? [{ id: 'speaker', label: 'Speakers', icon: <Users size={10} /> }]
                          : []),
                      ] as const).map((tab) => (
                        <button
                          key={tab.id}
                          onClick={() => setSummaryTab(tab.id as 'short' | 'detailed' | 'speaker')}
                          style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            padding: '.55rem .75rem',
                            fontSize: '.72rem', fontWeight: 700,
                            fontFamily: 'Inter, sans-serif',
                            textTransform: 'uppercase', letterSpacing: '.07em',
                            color: summaryTab === tab.id ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
                            borderBottom: summaryTab === tab.id ? '2px solid hsl(var(--accent))' : '2px solid transparent',
                            marginBottom: '-1px', transition: 'color .18s',
                            display: 'flex', alignItems: 'center', gap: '5px',
                          }}
                        >
                          {tab.icon} {tab.label}
                        </button>
                      ))}
                    </div>

                    {/* Short summary tab */}
                    {summaryTab === 'short' && resolvedShort && (
                      <div style={{ padding: '.85rem 1rem' }}>
                        <div style={{
                          background: 'linear-gradient(135deg, hsl(var(--accent) / .06), hsl(var(--accent) / .02))',
                          border: '1px solid hsl(var(--accent) / .2)',
                          borderLeft: '3px solid hsl(var(--accent))',
                          borderRadius: '8px', padding: '.8rem 1rem',
                        }}>
                          <p style={{
                            fontSize: '.85rem', color: 'hsl(var(--ink-soft))',
                            fontFamily: 'Inter, sans-serif', lineHeight: 1.7, margin: 0,
                          }}>
                            {resolvedShort}
                          </p>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '4px' }}>
                          <CopyButton text={resolvedShort} />
                        </div>
                      </div>
                    )}

                    {/* Detailed summary tab — full markdown */}
                    {summaryTab === 'detailed' && (
                      <div style={{ padding: '.85rem 1rem' }}>
                        {resolvedDetailed ? (
                          <>
                            <MarkdownContent content={resolvedDetailed} />
                            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '6px' }}>
                              <CopyButton text={resolvedDetailed} />
                            </div>
                          </>
                        ) : (
                          <p style={{ fontSize: '.82rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif', fontStyle: 'italic', margin: 0, textAlign: 'center', padding: '1rem 0' }}>
                            Detailed summary available for newly processed recordings.
                          </p>
                        )}
                      </div>
                    )}

                    {/* Speaker summary tab */}
                    {summaryTab === 'speaker' && speakerSummary && (
                      <div style={{ padding: '.85rem 1rem', display: 'flex', flexDirection: 'column', gap: '14px' }}>
                        {Object.entries(speakerSummary).map(([speaker, spData], idx) => (
                          <div
                            key={speaker}
                            style={{
                              background: 'hsl(var(--card))',
                              border: '1.5px solid hsl(var(--border) / .25)',
                              borderRadius: '8px', padding: '.8rem 1rem',
                              display: 'flex', flexDirection: 'column', gap: '8px',
                            }}
                          >
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                              <div style={{
                                width: '22px', height: '22px', borderRadius: '50%',
                                background: `hsl(${(idx * 137) % 360}, 65%, 50% / .15)`,
                                color: `hsl(${(idx * 137) % 360}, 65%, 50%)`,
                                display: 'flex', alignItems: 'center', justifyContent: 'center',
                                fontSize: '.65rem', fontWeight: 700, fontFamily: 'Inter, sans-serif',
                              }}>
                                {speaker.slice(0, 2).toUpperCase()}
                              </div>
                              <span style={{ fontWeight: 700, fontSize: '.85rem', color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif' }}>
                                {speaker}
                              </span>
                            </div>

                            {spData.summary && (
                              <p style={{ fontSize: '.8rem', color: 'hsl(var(--ink-soft))', margin: 0, lineHeight: 1.6, fontFamily: 'Inter, sans-serif' }}>
                                {spData.summary}
                              </p>
                            )}

                            {spData.key_points && spData.key_points.length > 0 && (
                              <div style={{ marginTop: '4px' }}>
                                <div style={{ fontSize: '.65rem', fontWeight: 750, color: 'hsl(var(--pencil))', textTransform: 'uppercase', letterSpacing: '.04em', marginBottom: '4px', fontFamily: 'Inter, sans-serif' }}>
                                  Key Points
                                </div>
                                {spData.key_points.map((kp, kIdx) => (
                                  <div key={kIdx} style={{ fontSize: '.78rem', color: 'hsl(var(--ink-soft))', paddingLeft: '.75rem', position: 'relative', marginBottom: '2px', lineHeight: 1.4, fontFamily: 'Inter, sans-serif' }}>
                                    <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--accent))' }}>•</span>
                                    {kp}
                                  </div>
                                ))}
                              </div>
                            )}

                            {spData.action_items && spData.action_items.length > 0 && (
                              <div style={{ marginTop: '4px' }}>
                                <div style={{ fontSize: '.65rem', fontWeight: 750, color: 'hsl(var(--pencil))', textTransform: 'uppercase', letterSpacing: '.04em', marginBottom: '4px', fontFamily: 'Inter, sans-serif' }}>
                                  Action Items
                                </div>
                                {spData.action_items.map((ai, aIdx) => (
                                  <div key={aIdx} style={{ fontSize: '.78rem', color: 'hsl(var(--ink-soft))', paddingLeft: '.75rem', position: 'relative', marginBottom: '2px', lineHeight: 1.4, fontFamily: 'Inter, sans-serif' }}>
                                    <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--success))' }}>•</span>
                                    {ai}
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                {/* Key points + action items */}
                {(keyPoints?.length || actionItems?.length) ? (
                  <div style={{ padding: '.9rem', display: 'flex', flexDirection: 'column', gap: '10px' }}>

                    {keyPoints && keyPoints.length > 0 && (
                      <div className="animate-slide-up" style={{
                        padding: '.9rem 1rem',
                        background: 'hsl(var(--card))',
                        borderRadius: '10px',
                        border: '1px solid hsl(var(--success) / .2)',
                        borderLeft: '3px solid hsl(var(--success))',
                      }}>
                        <div style={{
                          fontSize: '.68rem', fontWeight: 700,
                          color: 'hsl(var(--success))',
                          textTransform: 'uppercase', letterSpacing: '.09em',
                          marginBottom: '8px',
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                          fontFamily: 'Inter, sans-serif',
                        }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                            <FileText size={11} /> Key Points
                          </span>
                          <span style={{ background: 'hsl(var(--success) / .1)', padding: '.08rem .4rem', borderRadius: '999px', fontSize: '.62rem' }}>
                            {keyPoints.length}
                          </span>
                        </div>
                        {keyPoints.map((k, i) => (
                          <div key={i} style={{
                            fontSize: '.83rem', color: 'hsl(var(--ink-soft))',
                            marginBottom: '5px', paddingLeft: '.9rem', position: 'relative',
                            lineHeight: 1.65, fontFamily: 'Inter, sans-serif',
                          }}>
                            <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--success))', fontWeight: 700 }}>•</span>

                            <MarkdownContent content={k} />

                          </div>
                        ))}
                      </div>
                    )}

                    {actionItems && actionItems.length > 0 && (
                      <div className="animate-slide-up" style={{
                        padding: '.9rem 1rem',
                        background: 'hsl(var(--card))',
                        borderRadius: '10px',
                        border: '1px solid hsl(var(--accent) / .2)',
                        borderLeft: '3px solid hsl(var(--accent))',
                      }}>
                        <div style={{
                          fontSize: '.68rem', fontWeight: 700,
                          color: 'hsl(var(--accent))',
                          textTransform: 'uppercase', letterSpacing: '.09em',
                          marginBottom: '10px',
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                          fontFamily: 'Inter, sans-serif',
                        }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                            <ListChecks size={11} /> Action Items
                          </span>
                        </div>
                        <ActionItemsRenderer items={actionItems} />
                      </div>
                    )}

                  </div>
                ) : null}
              </>
            )}
          </>
        )}

        {/* ── Speakers Tab ── */}
        {recordingId && activeView === 'speakers' && (
          <SpeakerTab
            recordingId={recordingId}
            onScrollToSegment={onScrollToSegment ?? (() => {})}
            onTranscriptChanged={onTranscriptChanged ?? (() => {})}
          />
        )}

      </div>{/* end scroll container */}

      {/* Footer */}
      <div style={{
        padding: '.55rem 1rem',
        borderTop: '1px solid hsl(var(--border) / .15)',
        display: 'flex', alignItems: 'center', gap: '6px',
        flexShrink: 0,
        background: 'hsl(var(--card))',
      }}>
        <div style={{
          width: '7px', height: '7px', borderRadius: '50%',
          background: 'hsl(var(--success))',
          boxShadow: '0 0 6px hsl(var(--success) / .6)',
          flexShrink: 0,
        }} />
        <span style={{ fontSize: '.65rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif' }}>
          Local AI · Running locally · No internet required
        </span>
      </div>
    </div>
  )
}
